name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux (raw or zip)'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Clone egcd521/build-afdo repo (含 perf.data.zip)
        run: |
          git clone https://github.com/egcd521/build-afdo.git
          ls -lh build-afdo/perf.data.zip

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip curl

      - name: Download and extract create_afdo binary
        run: |
         curl -LO https://github.com/google/autofdo/releases/download/v0.30.1/create_llvm_prof-x86_64-v0.30.1.zip
         unzip create_llvm_prof-x86_64-v0.30.1.zip
         chmod +x create_afdo

      - name: Download vmlinux
        run: |
          curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux

      - name: Unzip perf.data.zip
        run: |
          unzip build-afdo/perf.data.zip
          ls -lh perf.data

      - name: Generate kernel.afdo
        run: |
          ./create_afdo --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo
