name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Direct download URL for vmlinux (raw or zip)'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout build-afdo repo (with perf.data.zip)
        uses: actions/checkout@v4
        with:
          repository: egcd521/build-afdo  # 你的仓库名
          ref: main  # 目标分支

      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y unzip curl

      - name: Download prebuilt create_afdo
        run: |
          curl -LO https://github.com/google/autofdo/releases/download/v0.21/create_afdo
          chmod +x create_afdo

      - name: Download vmlinux from input URL
        run: |
          curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux

      - name: Unzip perf.data.zip from the repo
        run: |
          unzip build-afdo/perf.data.zip -d .
          ls -lh perf.data

      - name: Generate kernel.afdo
        run: |
          ./create_afdo --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo
