name: Generate Kernel AFDO

on:
  workflow_dispatch:
    inputs:
      VMLINUX_URL:
        description: 'Download URL for vmlinux (artifact .zip or .raw)'
        required: true

jobs:
  generate-afdo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo (with perf.data.zip)
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ unzip zlib1g-dev

      - name: Clone and build create_afdo
        run: |
          git clone https://github.com/google/autofdo.git
          cd autofdo
          cmake -DCMAKE_BUILD_TYPE=Release .
          make -j$(nproc)
          cp create_afdo $GITHUB_WORKSPACE/

      - name: Download vmlinux
        run: |
          curl -L "${{ github.event.inputs.VMLINUX_URL }}" -o vmlinux

      - name: Unzip perf.data.zip
        run: |
          unzip perf.data.zip
          ls -lh perf.data

      - name: Generate kernel.afdo
        run: |
          chmod +x create_afdo
          ./create_afdo --binary=vmlinux --profile=perf.data --out=kernel.afdo

      - name: Upload kernel.afdo
        uses: actions/upload-artifact@v4
        with:
          name: kernel-afdo
          path: kernel.afdo
